language: objective-c
script: xcodebuild -workspace ArsScale.xcworkspace -scheme 'ArsScale' -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=YES clean build test | xcpretty -c
before_script: 
  - gem install xcpretty
